title: 𑀦𑀯𑀻𑀷𑁆
email: ""
description: >-
  GPU driver optimisation, program porting, and running SteamOS on PS5.
baseurl: ""
url: "https://naveentk1.github.io"
author: naveentk1

theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/naveentk1" }
    - { platform: twitter, user_url: "https://x.com/libgod1" }
    - { platform: rss, user_url: "/feed.xml" }
    - { platform: email, user_url: "mailto:naveentk325@gmail.com" }

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .git
